### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

### ISSUE THREAD

**Issue by its-Aman** [HsuanXyz/ion2-calendar#102]
Please fix it for Angular v5+. As `ngOutletContext` is replaced by `ngTemplateOutletContext` [detail](https://github.com/valor-software/ngx-bootstrap/issues/2658). 
See [here](https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecated-code) for deprecate code list.

**Comment by HsuanXyz** [comment]
This the plugin not used `[ngOutletContext]`, it is working in ionic`^3.9.0`.
Can you provide more information?

**Comment by its-Aman** [comment]
I just migrate my project from `ionic-angular` version `3.5.2` to `3.9.0` and all the `@angular/*` versions to `5.0.0` In my node module package `dayview.js`, `weekview.js` and `monthview.js` have `ngOutletContext` property bind to the respective properties. This was giving me the error `Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'`. Changing `ngOutletContext` to `ngTemplateOutletContext` solved my problem.

**Comment by valorkin** [comment]
fixed and published with https://github.com/valor-software/ngx-bootstrap/pull/2659
