### ISSUE TITLE
Extra space div

### ISSUE THREAD

**Issue by alexandre-pereira** [HsuanXyz/ion2-calendar#107]
![extra div](https://user-images.githubusercontent.com/6008032/33488861-620ac542-d6b2-11e7-9733-20e693eae888.png)

Hello,
Just noticed that this extra div make an extra blank space if the last day of the month is at the very end of the table row.

Would be nice to remove it as we will have more free space under the calendar.

Cheers,
Alex

**Comment by AltRoot17** [comment]
try to set of     `weekStart: 0, `

**Comment by alexandre-pereira** [comment]
It works, but that's not a proper fix as I need to have weekStart at 1. :(

**Comment by alexandre-pereira** [comment]
@HsuanXyz Any ideas how to bypass that? :)
