### ISSUE TITLE
有个Bug

### ISSUE THREAD

**Issue by chenbobowu** [HsuanXyz/ion2-calendar#11]
手机显示月份乱了。4月没有10月重复。电脑上面没问题。

**Comment by HsuanXyz** [comment]
你好，首先感谢你的issues。
我无法通过你的描述定位问题

可以的话我需要你告诉我以下信息：
1.在项目目录下执行 ionic info命令获取开发环境。
2.package.json 中 devDependencies与dependencies字段内容。
3.告诉我你的设备系统

**Comment by chenbobowu** [comment]
你GitHub的demo。

2017年4月22日 01:28，"Hsuan Lee" <notifications@github.com>写道：

**Comment by HsuanXyz** [comment]
@chenbobowu 我demo现在是开发环境，依赖并不稳定(表示歉意)
你可以新建一个项目然后在通过npm安装最新的发行版。

**Comment by chenbobowu** [comment]
我装最新的ionic3运行不了。typescript版本高了要修改成import Moment from moment才行。但是也是有这个Bug存在。

**Comment by HsuanXyz** [comment]
好的，我会在生成一个新的环境尝试重现。再次感谢

**Comment by chenbobowu** [comment]
太客气了。我们谢谢你写这么好的插件才对。

2017年4月22日 02:25，"Hsuan Lee" <notifications@github.com>写道：

**Comment by chenbobowu** [comment]
Contributing
    Fork it!
    Create your feature branch: git checkout -b my-new-feature
    Commit your changes: git commit -am 'Add some feature'
    Push to the branch: git push origin my-new-feature
    Submit a pull request :D

Development
cd ion2-calendar
npm install
npm run build
# output ./dist files

你好。 我Fork了Repo， 然后git clone到本地，接着创建支线。。。

然后我就想开发啦，但是我不知道怎么在本地测试这个src 或者是NPM生成的disk文件， 因为demo连接都不是连接本地的，我要开发只能修改src module，然后import module到Demo里面，最后bulid disk文件。。

不太懂git怎么合作，求教简单方法。。

我试了下：
cd ion2-calendar
npm install
npm run build （不成功）

**Comment by HsuanXyz** [comment]
报什么错

**Comment by chenbobowu** [comment]
C:\Users\George\Desktop\ion2-calendar>npm run bulid
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "bulid"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.8

npm ERR! missing script: bulid
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\George\Desktop\ion2-calendar\npm-debug.log

**Comment by HsuanXyz** [comment]
`npm run build` 不是  `npm run bulid`
