### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Hermiona** [HsuanXyz/ion2-calendar#115]
I want to change localization and I followed your instructions: installed moment.js and in app.module.ts wrote  the following:

```
@NgModule({
  ...
  providers: [{ provide: LOCALE_ID, useValue: "ru-RU" }]
})
```

In my calendar.ts  I wrote the following:
```
options: CalendarComponentOptions = {
    weekStart: 0,
    weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    monthPickerFormat: ['ЯНВ', 'ФЕВ', 'МАР', 'АПР', 'МАЙ', 'ИЮН', 'ИЮЛ', 'АВГ', 'СЕН', 'ОКТ', 'НОЯ', 'ДЕК'],
    monthFormat: 'MMM YYYY ',
  };
```
And in my calendar.html I have the following:
```
<ion-calendar [(ngModel)]="date"
              (onChange)="onChange($event)"
              [type]="type"
              [format]="'YYYY-MM-DD'"
              [options]="options">
</ion-calendar>
```
The result is that I get right months names only in the monthPicker. But a month title above the calendar stays in English all the time even after I pick another month.
Please, help me to fix this so that month title would be in right localization.

**Comment by HsuanXyz** [comment]
`ru-RU` not in the list https://github.com/angular/angular/tree/master/packages/common/locales
