### ISSUE TITLE
Refresh calendar?

### ISSUE THREAD

**Issue by shamank** [HsuanXyz/ion2-calendar#117]
Is there a way to refresh/reload the calendar in components mode?

**Comment by alexandre-pereira** [comment]
Would be nice, as when I update the CalendarComponentOptions I'ld like to have the "daysConfig" getting updated. Actually, it doesn't work.

**Comment by alexandre-pereira** [comment]
This is currently only updated if you switch the month.

**Comment by alexandre-pereira** [comment]
@HsuanXyz Could you please tell us if it's planned? :)

**Comment by HsuanXyz** [comment]
```ts
setTimeout(() => {
  const newOptions = {
      daysConfig: [ ... ]
  };
 
  // follows this
  this.options = {
      ...this.options,
      ...newOptions
  };
}, 2000)
```

**Comment by serra82** [comment]
Is there a way to refresh/reload the CalendarComponentOptions(daysConfig) also in modal mode?
After that calendar appear with myCalendar.present(); I push a page that change daysConfig, how can I update the calendar after this.navCtrl.pop(); ?

**Comment by HsuanXyz** [comment]
@serra82  Not yet supported

**Comment by alexandre-pereira** [comment]
thanks @HsuanXyz. Works perfectly.
