### ISSUE TITLE
Enable Past Days/Months

### ISSUE THREAD

**Issue by cdrock** [HsuanXyz/ion2-calendar#118]
Hello!

I'm currently using the range calendar, but all of the days/months prior to the current date are disabled.  Is there a way for me to enable them?

Cheers,
cdrock

**Comment by HsuanXyz** [comment]
#### Modal Mode

```ts
  openCalendar() {
    const options = {
      canBackwardsSelected: true,
      defaultDateRange: this.date,
      pickMode: 'range'
    };
    let myCalendar =  this.modalCtrl.create(CalendarModal, {
      options: options
    });

    myCalendar.present();

    myCalendar.onDidDismiss((date, type) => {
      if (date) {
          this.date = date;
      }
     })
  }
```

#### Components Mode
```html
      <ion-calendar [(ngModel)]="dateRange"
                    [options]="optionsRange">
      </ion-calendar>
```

```ts
import { Component } from '@angular/core';
import { CalendarComponentOptions } from 'ion2-calendar'
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  dateRange = { from: '2017-12-1'; to: '2017-12-25'; };
  optionsRange: CalendarComponentOptions = {
    from: new Date(1),
    pickMode: 'range'
  };
  constructor() { }
  ...
}
```

**Comment by iamhimesh** [comment]
How to disable future dates ?

**Comment by millemax** [comment]
> How to disable future dates

        var hoy=Date.now();
        const options: CalendarModalOptions = {
          canBackwardsSelected: true,
          pickMode: 'range',
          title: 'RANGE',
          to: hoy
        
        };

**Comment by sasos90** [comment]
@millemax this does not work for me. Where do you provide CalendarModalOptions then?

**Comment by jongbonga** [comment]
> @millemax this does not work for me. Where do you provide CalendarModalOptions then?
`
import { CalendarModalOptions } from 'ion2-calendar';`
