### ISSUE TITLE
Set from and to dates before opening calendar

### ISSUE THREAD

**Issue by yannbf** [HsuanXyz/ion2-calendar#12]
Hey! Thank you so much for opening this component. It looks really amazing!
I was wondering if it's possible to leave the from and to dates set, so if the user selects two dates and wants to change, he could then open the calendar up and see the selected dates there, then change.

Thanks once again!

**Comment by HsuanXyz** [comment]
Remember the last result？

**Comment by yannbf** [comment]
Exactly. The dates would already be selected.

**Comment by HsuanXyz** [comment]
![saved-dates](https://cloud.githubusercontent.com/assets/22736418/25751923/397d0ffe-31e9-11e7-9a9a-3a89fb8f9bcb.gif)
Is that so?

**Comment by yannbf** [comment]
Perfect! but I can one set the dates when loading the calendar? For instance, I get from and to dates from the server, and if I open the calendar, those dates would be set?
