### ISSUE TITLE
Getting error with command ionic cordova build --prod --release

### ISSUE THREAD

**Issue by avptechnocrats** [HsuanXyz/ion2-calendar#120]
I have a hybrid application built with ionic 2. I have used ion2-calendar plugin and I am getting error while building using command ionic Cordova build --prod --release . The error I am getting is no value accessor for form control with unspecified name attribute I have attached error sshot here. Can you please help me fixing this error as this has been a Do or Die situation for me? Thanks in advance!
![image](https://user-images.githubusercontent.com/5183515/34567634-0284ece6-f189-11e7-8301-09db0625cd9f.png)

**Comment by avptechnocrats** [comment]
@HsuanXyz , can you please take a look into my issue? I would really be thankful to you.

**Comment by HsuanXyz** [comment]
I can not get this error,  please `ionic init` a new project minimal reproduction.

My Environment:

```
cli packages: (/Users/hsuanlee/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0 browser 4.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v8.7.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/hsuanlee/Library/Android/sdk

```
