### ISSUE TITLE
Reset selected date

### ISSUE THREAD

**Issue by hairulardi** [HsuanXyz/ion2-calendar#128]
How to reset/remove selected date in date range?  
I create a button to reset the calendar and replace the date value,  it works if i set the value to:  
```
dateRange = {  
    from: "2018-01-30",  
    to: "2018-02-03"  
}
```  

But when i set the value to:  
```
dateRange = undefined;  
```
  
or  
  
```
dateRange = {  
    from: null,  
    to: null  
}
```  
The value changed but it doesn't clear the selected date.

**Comment by HsuanXyz** [comment]
`npm i ion2-calendar@beta`

**Comment by jongbonga** [comment]
how do I reset date on a multi pickMode?
