### ISSUE TITLE
No way to view current month that is open from controller ?

### ISSUE THREAD

**Issue by rahianeja** [HsuanXyz/ion2-calendar#129]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[- ] **3.x**
[ ] **4.x**

**Ion2-calendar version:**  

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[- ] feature request
[ ] help me

**Current behavior:**

When user navigates to say next month and does something on that page.
Currently if we want to fetch which view is open from outside calendar handler, there is no way to do that.

**Expected behavior:**

When we say this.currentMonth, it should return which month of the year is open in calendar.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by HsuanXyz** [comment]
components mode or modal mode ?

**Comment by rahianeja** [comment]
components mode..

**Comment by HsuanXyz** [comment]
`npm i ion2-calendar@beta` 

```ts
import { Component, ViewChild } from '@angular/core';

import {
  CalendarComponent,
  CalendarComponentOptions
} from 'ion2-calendar'

@Component({
  selector: 'demo-methods',
  template: `
    <ion-calendar #calendar ...>
    </ion-calendar>
  `
})
export class DemoMethodsComponent {
  ...
  @ViewChild('calendar', { read: CalendarComponent }) calendarRef: CalendarComponent;

  constructor() { }

  getCalendarViewDate() {
    console.log('view date', this.calendarRef.getViewDate())
  }

  serCalendarViewDate() {
    this.calendarRef.setViewDate('2018-02-01')
  }

}
```
