### ISSUE TITLE
How to remove day selected?

### ISSUE THREAD

**Issue by rahianeja** [HsuanXyz/ion2-calendar#130]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[- ] **3.x**
[ ] **4.x**

**Ion2-calendar version:**  

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[- ] help me

**Current behavior:**

Couldn't find a way to remove selected day.

**Expected behavior:**

Call a calendar inbuilt method to remove selected day.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by HsuanXyz** [comment]
components mode or modal mode ?

**Comment by rahianeja** [comment]
components mode

**Comment by HsuanXyz** [comment]
`npm i ion2-calendar@beta` and follows #128

**Comment by jongbonga** [comment]
just reset the ngModel to am empty array
