### ISSUE TITLE
在引用 modal模式下左右切换数据

### ISSUE THREAD

**Issue by DreamPWJ** [HsuanXyz/ion2-calendar#137]
能否只显示当前月的数据  现在是上滑显示  能否通过按钮左右切换控制  CalendarModalOptions参数里面没有这个参数

**Comment by HsuanXyz** [comment]
不支持，你可以在自定义模态框中实现。

![image](https://user-images.githubusercontent.com/22736418/36074336-d96d4132-0f79-11e8-97fa-bb9ef1fd9417.png)
