### ISSUE TITLE
Custom text/background color for different days

### ISSUE THREAD

**Issue by roudikk** [hsuanxyz/ion2-calendar#143]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[X] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] help me

**Current behavior:**
Can't find a way to set custom background for different days, for example if i have multiple event "types" and each type should be of some color

**Expected behavior:**
To be able to change the day text/background color

**Comment by cbracamonte** [comment]
I think it can not be done at the moment, since everyone handles the same class in the css, the only thing similar is to add it to the calendar as days_config (it accepts custom class)

**Comment by jlcasasg** [comment]
@cbracamonte  Do you have an example of doing this?

**Comment by cbracamonte** [comment]
@jlcasasg Of course, here is an example :)

//Declare an object with the properties for CalendarComponentOptions

 options: CalendarComponentOptions = {
        showMonthPicker: false,
        pickMode: 'multi',
        weekdays: this.days,
        disableWeeks: [0, 6],
    };
_daysConfig: DayConfig[] = [];

//event
 optionsCalendar() {
        this.options = {
            showMonthPicker: false,
            pickMode: 'multi',
            weekdays: this.days,
            daysConfig: this._daysConfig,
            disableWeeks: [0, 6],
        };
    }


//In my case I want Saturdays and Sundays to have red color

daysConfig() {
        var inicio = new Date("2018-01-01");
        var fin = new Date("2020-12-31");
        var timeDiff = Math.abs(fin.getTime() - inicio.getTime());
        var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));
        var daysConfig = new Array();
        //Sundays - Saturdays
        for (var j = 0; j <= diffDays; j++) {
            if (inicio.getDay() == 0 || inicio.getDay() == 6) {
                this._daysConfig.push({ date: new Date(inicio.getTime()), cssClass: 'my-day' })
            }
            inicio.setDate(inicio.getDate() + 1);
        }
        return daysConfig;
    }

Note: You can create different arrays with fields that DayConfig asks you for (see documentation).
export interface DayConfig {
    date: Date;
    marked?: boolean;
    disable?: boolean;
    title?: string;
    subTitle?: string;
    cssClass?: string;
}

Any questions you ask me.
