### ISSUE TITLE
How can i prevent the user for unselect a date?

### ISSUE THREAD

**Issue by andredatsch** [HsuanXyz/ion2-calendar#144]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[X ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ X] help me

On my app, the user will select the days, and add stuffs to that day, when a day already has stuffs on it, it can`t be unselected, how can i prevent the user from unselecting a specific date?

**Comment by cbracamonte** [comment]
in the onSelect event, ask if your product array has more than 1 item, then you can go to the product page, if it does not show a popup that can not fill that day anymore.
