### ISSUE TITLE
Displaying previous month last days at start of current month

### ISSUE THREAD

**Issue by ValdoGhafoor** [HsuanXyz/ion2-calendar#148]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[X] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[X] help me

## Displaying previous month last days in the free space at start of current month

Hello !
First, thanks for your work on this calendar, it saved my life.

I would love to achieve what is in this attached file:
Displaying last days of previous month in the free space at start of current month.
As you can see, 29th 30th 31th are displaying before the 1st
Do you know a way to do it ?

Thanks ! 

<img width="687" alt="capture d ecran 2018-02-23 a 15 51 17" src="https://user-images.githubusercontent.com/7875009/36600150-cce1f156-18b1-11e8-81fa-4d9295d9797d.png">

**Comment by HsuanXyz** [comment]
```bash
$ npm i ion2-calendar@beta
```
![image](https://user-images.githubusercontent.com/22736418/36624412-cd63a262-1949-11e8-92d0-644ff962af31.png)

**Comment by ValdoGhafoor** [comment]
Hello,

I'm working with date range, that's why I couldn't see this.
Is it intentionally disabled for date ranges ?
