### ISSUE TITLE
Scroll isn't working in ios

### ISSUE THREAD

**Issue by jordiigarciaa** [HsuanXyz/ion2-calendar#15]
At browser works well, but in ios only shows 3 months and doesn't scrolls.

**Comment by HsuanXyz** [comment]
Tell me your Ionic Framework Version

**Comment by HsuanXyz** [comment]
https://github.com/driftyco/ionic/issues/10976

update your Ionic Framework Version to >v3.0.1

**Comment by jordiigarciaa** [comment]
people said that is working on 2.2, isn't it? i will need to make a lot of changes if i want upgrade to 3.0, and the majority of plugins aren't working yet.
Thanks for your work and your help, i will play prooving it.

**Comment by jordiigarciaa** [comment]
Confirmed, its working in 2.2. 
Thanks!

**Comment by guillaume-roy** [comment]
@jordiigarciaa How did you fixed this issue ?
