### ISSUE TITLE
how to show selected dates in ion-2 calendar

### ISSUE THREAD

**Issue by mebinvarghese** [HsuanXyz/ion2-calendar#156]
**Current behavior:**
When we select dates from multi calendar it return values, when open again the selected values are gone from calendar

**Expected behavior:**
selected dates must show in calendar when it open

**Comment by HsuanXyz** [comment]
setting `defaultDates` in the options

**Comment by mebinvarghese** [comment]
@HsuanXyz Thanks for you valuable response

I want know one more thing. Is it possible to select all Monday from calendar?

**Comment by HsuanXyz** [comment]
not supported now

**Comment by mebinvarghese** [comment]
Huh, How can we implement that
