### ISSUE TITLE
Can i show calendar created in components mode in the same way as calendar created in modal mode?

### ISSUE THREAD

**Issue by alenmestrov** [HsuanXyz/ion2-calendar#158]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[x ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] help me

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**
Hi, I'm new to Ionic development and maybe this question is out of place but i can't find answer anywhere is this even doable or not. Thank you in advance for reading it.
So, currently created calendar in component mode is presented in slide view (month after month) and in modal mode view is presented in list view (month beneath month). Is there a way in which I can show component mode created calendar in the same way as modal mode created calendar.
Thank you in advance, 
Alen

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by HsuanXyz** [comment]
Sorry, it is not supported yet.
