### ISSUE TITLE
How to select a year in a datepicker?

### ISSUE THREAD

**Issue by akaNightmare** [HsuanXyz/ion2-calendar#159]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[x] components mode
[] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] help me

**Current behavior:**
I am wondering how to select a year in the date picker.

**Expected behavior:**
It would be great to select a year something like day and month.

**Comment by HsuanXyz** [comment]
Switch to month selection then use the direction button
