### ISSUE TITLE
Android calendar scroll

### ISSUE THREAD

**Issue by kustrun** [HsuanXyz/ion2-calendar#197]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[x] modal mode

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] help me

**Current behavior:**
If Ionic application is used as hybrid application (save website from mobile browser as shortcut to the device desktop) there occurs a bug while displaying the calendar months. On Android devices the data is displayed only for 2 months.
![image](https://user-images.githubusercontent.com/9192608/44203710-4280e800-a150-11e8-925f-7e0b9ec40cb9.png)

**Expected behavior:**
On Android devices users should be able to scroll between months.

**Steps to reproduce:**
In web browser:
1. Open application.
2. Open calendar and try to scroll (scroll does not work).

As HTML5 application:
1. Open Ionic app in mobile web broswer.
2. In options add application to Home screen (i.e. on mobile Chrome browser click Add to Home screen).
3. Open application from the deskstop.
4. Open calendar and try to scroll (scroll does not work).

**Other information:**
Bug appeared on Nexus 7 with Android version 6. 0. 1 and on Galaxy S9+ with Android version 8. 0. 0.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.0.6
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

System:

   NodeJS : v8.11.3
   npm    : 6.2.0
   OS     : Windows 10
```

**Comment by nuriodaci** [comment]
Same issue.Do you have any solution ?

**Comment by kustrun** [comment]
No, not yet. I did not figure it out yet.

**Comment by ulesta** [comment]
@kustrun Hi there, have you tried the latest release, `3.0.0`? This release supports Ionic 4. All previous releases did not.
