### ISSUE TITLE
Calendar not closing when clicking on a date

### ISSUE THREAD

**Issue by gustavofulton** [HsuanXyz/ion2-calendar#21]
I don't understand why the calendar needs to close when clicking on a date. It could just return a JSON about that specific date, but closing it makes no sense to me.

Also, wrapping in a component (as someone already said) would make this calendar VERY popular.

**Comment by HsuanXyz** [comment]
>English is not my native language; please excuse typing errors.

The beginning is for my own needs, in the design made some mistakes.
Now, these two features as well as confirm the addition, please wait 2.0 version.

**Comment by gustavofulton** [comment]
Do you have any date prediction? I was trying to implement in a project now and those features would really come to hand 👍

**Comment by HsuanXyz** [comment]
A temporary way in this version:
Provide a callback function before closing , through a Boolean to determine whether to close.

Is this okay?

**Comment by RakeshKW** [comment]
how to provide callback function before closing....
