### ISSUE TITLE
Ionic 4 error configuration

### ISSUE THREAD

**Issue by stoppiNeobiz** [hsuanxyz/ion2-calendar#215]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[x] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] help me

Hi, after configuration I recite this error:
StaticInjectorError(AppModule)[Icon -> Config]: ....
 StaticInjectorError(Platform: core)[Icon -> Config]: 
    NullInjectorError: No provider for Config!

I've import CalendarModule on app.module.ts and my page.module.ts

thanks

**Comment by stoppiNeobiz** [comment]
no help?

**Comment by Rift-Walker** [comment]
Config has been changed to IonConfig in ionic 4. I'm working on updating my fork for these changes.

**Comment by manmohanagarwal4** [comment]
same error here. 
Did you resolve it?

**Comment by happy2share** [comment]
Working for me by using dev branch and loading lazily within the page required. I have used **range** as _pickMode_. Here is the sample:

**test.html**:
```
<ion-content padding>
  <ion-calendar [(ngModel)]="dateRange"
                (change)="onChange($event)"
                [type]="type"
                [format]="'YYYY-MM-DD'"
                [options]="optionsRange">
   </ion-calendar>
</ion-content>
```
**test.page.ts:**

```
import { Component, OnInit } from '@angular/core';

import { CalendarComponentOptions } from '../components/ion2-calendar';
import * as moment from 'moment';

@Component({
  selector: 'app-test',
  templateUrl: './test.page.html',
  styleUrls: ['./test.page.scss'],
})
export class TestPage implements OnInit {

  dateRange: { from: string; to: string; };
  type: 'string'; // 'string' | 'js-date' | 'moment' | 'time' | 'object'

  optionsRange: CalendarComponentOptions = {
    pickMode: 'range',
  };
  address: Object;

  constructor() { }

  ngOnInit() {
    this.menuCtrl.enable(true);
    this.address = {
      place: ''
    };
  }

  onChange($event: any) {
    console.log($event);
  }
}
```
**test.module.ts**

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Routes, RouterModule } from '@angular/router';

import { IonicModule } from '@ionic/angular';
import { CalendarModule } from '../components/ion2-calendar';

import { TestPage } from './test.page';

const routes: Routes = [
  {
    path: '',
    component: TestPage
  }
];

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    RouterModule.forChild(routes),
    CalendarModule
  ],
  declarations: [TestPage]
})
export class TestPageModule {}
```

**Comment by alpesh12** [comment]
have you tried [this](https://www.logisticinfotech.com/blog/ionic4-datepicker-component/)?

**Comment by ulesta** [comment]
@stoppiNeobiz Which version of Ionic 4 are you running?

**Comment by ulesta** [comment]
@alpesh12 This isn't the place to advertise your own calendar library, please be considerate of the developers who are in need of support. Thank you.

**Comment by alpesh12** [comment]
Okay

**Comment by obkdev** [comment]
I'm having the same problem. I have implemented @happy2share 's code and am still facing the same issue. I must be leaving something out. What does your app.module.ts look like?
