### ISSUE TITLE
Svg icons not showing with Ionic rc-1

### ISSUE THREAD

**Issue by selipso** [HsuanXyz/ion2-calendar#217]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[X] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[X] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] help me

**Current behavior:**

The icons to go forward and backward in the month view do not show up. Instead, the following error messages are shown in the console for not getting the right Ionicon .svgs

```
GET http://localhost:8100/svg/md-arrow-dropdown.svg 404 (Not Found)
GET http://localhost:8100/svg/ios-arrow-back.svg 404 (Not Found)
GET http://localhost:8100/svg/ios-arrow-forward.svg 404 (Not Found)
```

**Expected behavior:**

Arrow Icon and dropdown icons show up and are visible.

**Steps to reproduce:**

**Related code:**

```
<ion-content>
  <ion-calendar
    [(ngModel)]="date"
    (onChange)="onChange($event)"
    [type]="calDateType"
    [format]="'YYYY-MM-DD'"
  ></ion-calendar>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/home/thakker/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.9.0-rc.3
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (3 plugins total)

System:

   NodeJS : v10.14.1 (/home/thakker/.nvm/versions/node/v10.14.1/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15
```

**Comment by ulesta** [comment]
Hi @selipso ! Looks like a breaking change was introduced in Ionic `4.0.0-rc.1`, if you are using this version or newer, add the following to your project's `angular.json` and you should be good to go!

![image](https://user-images.githubusercontent.com/3767490/51316410-91de8380-1a22-11e9-8936-91a5217c887d.png)

For more info: https://github.com/ionic-team/ionic/releases/tag/v4.0.0-rc.1
