### ISSUE TITLE
Events not triggering

### ISSUE THREAD

**Issue by idanzapp** [HsuanXyz/ion2-calendar#218]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ x ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ x  ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ x  ] bug report
[ ] feature request
[ ] help me

**Current behavior:**

When I click a day, the event is not triggering

**Expected behavior:**

When I click a day, the event triggers

**Steps to reproduce:**

Just use the basic configuration o the lastest ionic 4 build

**Related code:**

```
<ion-calendar 
        (onSelect)="select($event)"
              [type]="type"
              [format]="'DD-MM-YYYY'">
    </ion-calendar> 
```

```
type: 'string' | 'js-date' | 'moment' | 'time' | 'object' = 'string'

  constructor() { } 

  select(event) {
    console.log('hi', event)
  }
```

**Other information:**
Before clicking, nothing appears on console (expected)

![start](https://user-images.githubusercontent.com/26038595/51304466-88f8ac80-1a38-11e9-8657-2a136d712741.png)

After cicking, nothing appears on console (expected behaviour: ' hi [dateArray]')
![selected](https://user-images.githubusercontent.com/26038595/51304465-88f8ac80-1a38-11e9-852b-54a95e0e1716.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (C:\Users\Samir\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Samir\AppData\Local\Android\Sdk)
   NodeJS            : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by idanzapp** [comment]
Finally, at least in ionic 4, the events are without the on (onSelect) should be (select)

**Comment by ulesta** [comment]
@idanzapp yep! Haven't gotten around to updating the docs, but I'll be updating them over the weekend to reflect this. As per Angular styleguide, we shouldn't prefix output bindings with `on`: https://angular.io/guide/styleguide#style-05-16

Sorry for the confusion! 😄
