### ISSUE TITLE
cannot find name ModalController etc

### ISSUE THREAD

**Issue by richardshergold** [HsuanXyz/ion2-calendar#221]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x] help me

**Current behaviour:**

App won't run after installing package
**Expected behaviour:**

App should run
**Steps to reproduce:**

npm install ion2-calendar@next moment --save
ionic serve
**Related code:**

```
insert short code snippets here
```

**Other information:**

When I add the package and run ionic serve I get the following errors 

[app-scripts] [15:41:34]  ionic-app-scripts 3.1.11
[app-scripts] [15:41:34]  watch started ...
[app-scripts] [15:41:34]  build dev started ...
[app-scripts] [15:41:34]  clean started ...
[app-scripts] [15:41:34]  clean finished in 1 ms
[app-scripts] [15:41:34]  copy started ...
[app-scripts] [15:41:34]  deeplinks started ...
[app-scripts] [15:41:35]  deeplinks finished in 411 ms
[app-scripts] [15:41:35]  transpile started ...
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/calendar.controller.d.ts, line: 5
[app-scripts]             Cannot find name 'ModalController'.
[app-scripts]        L4:  export declare class CalendarController {
[app-scripts]        L5:      modalCtrl: ModalController;
[app-scripts]        L6:      calSvc: CalendarService;
[app-scripts]             Cannot find name 'ModalController'.
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/calendar.controller.d.ts, line: 7
[app-scripts]        L6:  calSvc: CalendarService;
[app-scripts]        L7:  constructor(modalCtrl: ModalController, calSvc: CalendarService);
[app-scripts]             Cannot find name 'AnimationBuilder'.
[app-scripts]       L42:  backdropDismiss?: boolean;
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/calendar.model.d.ts, line: 43
[app-scripts]       L43:  enterAnimation?: AnimationBuilder;
[app-scripts]       L44:  leaveAnimation?: AnimationBuilder;
[app-scripts]             Cannot find name 'AnimationBuilder'.
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/calendar.model.d.ts, line: 44
[app-scripts]       L43:      enterAnimation?: AnimationBuilder;
[app-scripts]       L44:      leaveAnimation?: AnimationBuilder;
[app-scripts]             Cannot find name 'ModalController'.
[app-scripts]        L3:  import { CalendarService } from './services/calendar.service';
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/calendar.module.d.ts, line: 4
[app-scripts]        L4:  export declare function calendarController(modalCtrl: ModalController, calSvc: CalendarService): CalendarCon
[app-scripts]        L5:  export declare class CalendarModule {
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/components/calendar.modal.d.ts, line: 8
[app-scripts]             Cannot find name 'NavParams'.
[app-scripts]        L7:  _elementRef: ElementRef;
[app-scripts]        L8:  params: NavParams;
[app-scripts]        L9:  modalCtrl: ModalController;
[app-scripts]             Cannot find name 'ModalController'.
[app-scripts]        L8:  params: NavParams;
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/components/calendar.modal.d.ts, line: 9
[app-scripts]        L9:  modalCtrl: ModalController;
[app-scripts]       L10:  ref: ChangeDetectorRef;
[app-scripts]             Cannot find name 'IonContent'.
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/components/calendar.modal.d.ts, line: 12
[app-scripts]       L11:  calSvc: CalendarService;
[app-scripts]       L12:  content: IonContent;
[app-scripts]       L13:  monthsEle: ElementRef;
[app-scripts]             Cannot find name 'NavParams'.
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/components/calendar.modal.d.ts, line: 25
[app-scripts]       L24:  actualFirstTime: number;
[app-scripts]       L25:  tor(_renderer: Renderer2, _elementRef: ElementRef, params: NavParams, modalCtrl: ModalController, ref: Chang
[app-scripts]       L26:  ngOnInit(): void;
[app-scripts]             Cannot find name 'ModalController'.
[app-scripts] [15:41:39]  typescript: node_modules/ion2-calendar/dist/components/calendar.modal.d.ts, line: 25
[app-scripts]       L24:  actualFirstTime: number;
[app-scripts]       L25:  erer2, _elementRef: ElementRef, params: NavParams, modalCtrl: ModalController, ref: ChangeDetectorRef, calSv
[app-scripts]       L26:  ngOnInit(): void;

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/richardshergold/.nvm/versions/node/v8.12.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 20 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.12.0 (/Users/richardshergold/.nvm/versions/node/v8.12.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by vov4ik08** [comment]
How to fix ?

**Comment by aluferraz** [comment]
How to fix ?
