### ISSUE TITLE
[Bug] Some months are not shown on modal mode

### ISSUE THREAD

**Issue by rodrigojrmartinez** [hsuanxyz/ion2-calendar#229]
**Ionic version:** 
[ ] **2.x**
[ ] **3.x**
[X ] **4.x**

**Ion2-calendar mode:** 
[ ] components mode
[ X] modal mode

**I'm submitting a ...** 
[ X] bug report
[ ] feature request
[ ] help me

**Current behavior:**
Currently when opening a modal calendar with a defined from / to dates to be selectables, in between there are some months that doesn't show which seems quite weird

**Expected behavior:**
All months between the from / to specified dates should be selectable

**Steps to reproduce:**
Define a modal calendar with a from Date (lets day a month ago from today) and a to Date in the future (lets say one year from today)

**Related code:**

```
  async createCalendarModal() {
    const options = await this.getCalendarOptions();
    const modal = await this._mc.create({
      component: CalendarModal,
      componentProps: { options },
      animated: true
    });
    return modal;
  }
```

The options returned by the getCalendar Options are (as returned from console log):

```
title: "Select a Date"
closeLabel: "Cancel"
doneLabel: "Done"
pickMode: "range"
from: Sun Jan 27 2019 21:00:00 GMT-0300 {} (Date Object)
to: Wed Dec 30 2020 21:00:00 GMT-0300 {} (Date Object)
```

**Other information:**

**Screenshot**:

![calendarbug](https://user-images.githubusercontent.com/45562671/53648537-e2025580-3c1e-11e9-8a80-f7b22512ae7d.PNG)

**Ionic info:**:

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (C:\Users\rodrigomartinezjr\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.0, (and 12 other plugins)

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.7.0
   OS     : Windows 10
```

Thanks! Great Plugin, super easy and quite complete!

**Comment by jeyaraj87** [comment]
I am also facing this issue in my application. Any idea when this will be resolved.

**Comment by mmsanchezlatorre** [comment]
I had the same problem. I solved it by modifying the calendar.modal.js file. You can find it in the components folder. On line 124 change:
`.add(NUM_OF_MONTHS_TO_CREATE, 'M')`

to:
`.add(1, 'M')`

**Comment by ulesta** [comment]
Hey all, will be looking into this this week

**Comment by ulesta** [comment]
Hello! Just a quick update, this will be fixed when this PR gets merged: https://github.com/hsuanxyz/ion2-calendar/pull/263
