### ISSUE TITLE
CalendarModule import not working

### ISSUE THREAD

**Issue by Mo5005** [HsuanXyz/ion2-calendar#231]
![12](https://user-images.githubusercontent.com/39675817/53813159-4a25a400-3f5d-11e9-9cfe-ae566b97db66.JPG)

```
>ionic version
4.9.0

Angular CLI: 7.2.4
Node: 10.13.0
OS: win32 x64
Angular: 7.2.5
```

please for quick help

**Comment by Mo5005** [comment]
I wrote that in module page and then the error comes
`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';
import { Calendar } from '@ionic-native/calendar/ngx';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { CalendarModule } from "ion2-calendar";

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    CalendarModule, 
    BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    Calendar,
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
`
someone help

**Comment by Mo5005** [comment]
@HsuanXyz i need some help please

**Comment by ulesta** [comment]
It could be because you haven’t installed release with Ionic v4 support. Try this: 

install ion2-calendar@next moment --save

**Comment by Mo5005** [comment]
I tried that and it worked, thanks
but I have another question, how do I get the data from the calendar from Components Mode?

**Comment by ulesta** [comment]
@Mo5005 see https://github.com/HsuanXyz/ion2-calendar#basic

**Comment by Mo5005** [comment]
I tried to work with date to add an event but it still does not work 
can you please help me how to add an event to the Calendar?

**Comment by Mo5005** [comment]
I did it that way, but it does not really work
`

  async presentAlertPrompt() {
    const alert = await this.alertController.create({
      header: 'Select yor time!',
      inputs: [

        // input date with min & max
        {
          placeholder: '00:00',
          name: 'startTime',
          type: 'time',
          handler: () => {
          }
        },
        {
          name: 'endTime',
          type: 'time',
          placeholder: '01:00',
        }
      ],
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          cssClass: 'secondary',
          handler: (v) => {
            console.log('Confirm Cancel');

          }
        }, {
          text: 'Ok',
          handler: (v) => { 
            
            let temp = this.events
            

            this.event.startTime =  new Date(v.startTime);
            this.event.endTime = new Date( v.endTime);
            this.event.date = this.selectedDay

            temp.push(this.event)
            this.events = []
            this.events = temp


            console.log(this.event)
            console.log('---------------------')
            console.log(this.events) 


          }
        }
      ]
    });

    await alert.present();
  }


`
html code 
`
<ion-content>


  
  <ion-fab vertical="bottom" horizontal="end" slot="fixed">
    <ion-fab-button (click)="presentAlertPrompt()">
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
  </ion-fab>
 

  <ion-calendar [(ngModel)]="date" (change)="onChange($event)" (select)="onSelect($event)"
    (selectStart)="onSelectStart($event)" (selectEnd)="onSelectEnd($event)" [type]="type" [format]="'YYYY-MM-DD'"
    [options]="optionsCal">
  </ion-calendar>



  <div *ngFor="let event of events">
    <div *ngIf="event.date == selectedDay ">
      <ion-item>
        {{event.startTime}}
      </ion-item>
    </div>

  </div>
 
</ion-content>
`

**Comment by Mo5005** [comment]
html code 
 `
<ion-content>

  
  <ion-fab vertical="bottom" horizontal="end" slot="fixed">
    <ion-fab-button (click)="presentAlertPrompt()">
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
  </ion-fab>
 
  <ion-calendar [(ngModel)]="date" (change)="onChange($event)" (select)="onSelect($event)"
    (selectStart)="onSelectStart($event)" (selectEnd)="onSelectEnd($event)" [type]="type" [format]="'YYYY-MM-DD'"
    [options]="optionsCal">
  </ion-calendar>

  <div *ngFor="let event of events">
    <div *ngIf="event.date == selectedDay ">
      <ion-item>
        {{event.startTime}}
      </ion-item>
    </div>
  </div>
</ion-content>`

**Comment by Mo5005** [comment]
`<ion-content>


  
  <ion-fab vertical="bottom" horizontal="end" slot="fixed">
    <ion-fab-button (click)="presentAlertPrompt()">
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
  </ion-fab>
 

  <ion-calendar [(ngModel)]="date" (change)="onChange($event)" (select)="onSelect($event)"
    (selectStart)="onSelectStart($event)" (selectEnd)="onSelectEnd($event)" [type]="type" [format]="'YYYY-MM-DD'"
    [options]="optionsCal">
  </ion-calendar>



  <div *ngFor="let event of events">
    <div *ngIf="event.date == selectedDay ">
      <ion-item>
        {{event.startTime}}
      </ion-item>
    </div>

  </div>
 
</ion-content>`
