### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof CalendarModule'

### ISSUE THREAD

**Issue by YogliB** [hsuanxyz/ion2-calendar#239]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[x] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] help me

**Current behavior:**
When trying to use `.forRoot({...})`, I'm getting:
```
Property 'forRoot' does not exist on type 'typeof CalendarModule'.
```

**Expected behavior:**
`.forRoot()` existing and not getting an error.

**Steps to reproduce:**
```
npm install ion2-calendar@next moment --save
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\yogib\scoop\persist\nodejs-lts\bin\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\yogib\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Users\yogib\scoop\apps\nodejs-lts\current\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by frankyso** [comment]
same here

**Comment by jicarrozzo** [comment]
Same problem here.. with 4.x

**Comment by laxmantandon** [comment]
Getting Same problem, any work around

**Comment by frankyso** [comment]
i think this plugin doesn't maintenance any more

**Comment by ulesta** [comment]
Hey Franky, this plugin is still being maintained. I’ll have a look soon.

**Comment by ulesta** [comment]
@YogliB from the looks of it, your Ionic version is running on `3.x`, *version `3.0.0-rc.0` of this plugin will only for for Ionic@4.x*

**Comment by ulesta** [comment]
Feel free to re-open if `npm install ion2-calendar@next moment --save` still gives issues on `@ionic/angular@4.x`

**Comment by vyzaldysanchez** [comment]
I'm still having this issue using `@ionic/angular 4.9.1`. Any workaround?

**Comment by Sroose** [comment]
same here, when using the forRoot
