### ISSUE TITLE
ERROR in node_modules/ion2-calendar/dist/calendar.controller.d.ts:1:33 - error TS2307: Cannot find module 'ionic-angular'. [ng] 1 import { ModalController } from 'ionic-angular';

### ISSUE THREAD

**Issue by VigneshMohanrajInvensis** [hsuanxyz/ion2-calendar#266]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ x] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[x ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] help me

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
ERROR in node_modules/ion2-calendar/dist/calendar.controller.d.ts:1:33 - error TS2307: Cannot find module 'ionic-angular'.
[ng] 1 import { ModalController } from 'ionic-angular';
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by EDcasa** [comment]
I had the same problem and I solved it with npm install ion2-calendar@next moment --save

**Comment by VigneshMohanrajInvensis** [comment]
> I had the same problem and I solved it with npm install ion2-calendar@next moment --save

Thanks @EDcasa .. it worked for me.

**Comment by tomavic** [comment]
I tried the command above and still got the same error

**Comment by tatianilima** [comment]
same problem here
