### ISSUE TITLE
Missing months as shown on the demo. Can't show more than 11 months in sequence.

### ISSUE THREAD

**Issue by jcmendes9898** [hsuanxyz/ion2-calendar#273]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] help me

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
More detail in here: 
https://stackoverflow.com/questions/58937453/ion2-calendar-error-when-showing-months-from-a-selected-year

**Comment by mejdan** [comment]
Same issue 
ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
Ionic Framework               : @ionic/angular 4.1.1

ion2-calendar modal mode 
if I scroll from January 2020 to the end of year December 2020 and January 2021 are missing.

**Comment by heyypatrick** [comment]
> Same issue
> ionic (Ionic CLI) : 4.10.2 (/usr/local/lib/node_modules/ionic)
> Ionic Framework : @ionic/angular 4.1.1
> 
> ion2-calendar modal mode
> if I scroll from January 2020 to the end of year December 2020 and January 2021 are missing.

have you already fixed it?

**Comment by heyypatrick** [comment]
> > Same issue
> > ionic (Ionic CLI) : 4.10.2 (/usr/local/lib/node_modules/ionic)
> > Ionic Framework : @ionic/angular 4.1.1
> > ion2-calendar modal mode
> > if I scroll from January 2020 to the end of year December 2020 and January 2021 are missing.
> 
> have you already fixed it @mejdan?

UPDATE: 
I already fixed it. I edited `calendar.modal.js` line 17 `NUM_OF_MONTHS_TO_CREATE` value to `1` from `3`.

**Comment by jcmendes9898** [comment]
One question, Do you know how to make the modal to be readonly?

**Comment by heyypatrick** [comment]
> One question, Do you know how to make the modal to be readonly?
Ohh, I see. I haven't tried it yet.

**Comment by jcmendes9898** [comment]
yes, it worked. Although I'm currently using ionic2-calendar. It works as fine, but it's not as appealing as this one. The modal one. If I managed to make it to be readonly it would be perfect.
