### ISSUE TITLE
How to disable future dates

### ISSUE THREAD

**Issue by shubhamappstec** [hsuanxyz/ion2-calendar#277]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[x] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[x] help me

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
   Ionic CLI                     : 5.4.13
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:
   cordova-res : 0.8.1
   native-run  : 0.3.0

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v10.16.2
   npm               : 6.9.0
   OS                : Windows 10

**Comment by shubhamkhuva** [comment]
Here is solution:
 const options: CalendarModalOptions = {
      pickMode: 'range',
      title: 'Select Date',
      canBackwardsSelected: true,
      to:new Date()
    };
