### ISSUE TITLE
Ionicons 5 breaking changes

### ISSUE THREAD

**Issue by jongbonga** [hsuanxyz/ion2-calendar#283]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**
[x] **5.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] help me

**Current behavior:**

Ionicons 5 comes with renamed icons that causes buttons to disappear on calendar

**Expected behavior:**

Show all the icons/button

**Steps to reproduce:**

update to latest ionic 5

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.3
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2
```

**Comment by TdoubleG** [comment]
+1

**Comment by shaneparsons** [comment]
@jongbonga @TdoubleG Until ionicon 5 support is merged into this repo, feel free to point towards the latest commit in my fork:
```json
"ion2-calendar": "https://github.com/shaneparsons/ion2-calendar#93a2b3a58b3117540b4f994708fe3076f1877757",
```

**Comment by javieraviles** [comment]
Thanks @shaneparsons 

Why is not being merged to main project yet? is the owner lacking time for this or?

**Comment by aastudillo91** [comment]
> @jongbonga @TdoubleG Until ionicon 5 support is merged into this repo, feel free to point towards the latest commit in my fork:
> 
> ```json
> "ion2-calendar": "https://github.com/shaneparsons/ion2-calendar#76ae1e241183500a377647b363c931a03aa50bca",
> ```


shane install your fork repository but still can't load the icons, this is my log:

[WDS] Live Reloading enabled.
svg/md-arrow-dropdown.svg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
svg/ios-arrow-back.svg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
svg/ios-arrow-forward.svg:1 Failed to load resource: the server responded with a status of 404 (Not Found)

this is my ionic info log:
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.1.2

Utility:

   cordova-res (update available: 0.15.1) : 0.13.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.2 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

does the same error happen to someone else?
or
can you help me solve this problem?

thanks!!

**Comment by shaneparsons** [comment]
@aastudillo91 I'm not sure how you're using the component in order to get those errors, but here's an example of how I'm using it, without issues:
```vue
<template>
    <full-calendar :config="config" :events="events" />
</template>

<script>
export default {
  data() {
    return {
      config: {
        defaultView: 'month',
        themeSystem: 'bootstrap4',
        header: {
          left: 'title',
          center: '',
          right: 'prev,today,next',
        },
        buttonText: {
          prev: '<',
          today: 'Today',
          next: '>',
        },
        bootstrapFontAwesome: false,
        eventClick: item => {
          console.log(item.id);
        },
      },
      events: [
        {
          title: 'event1',
          start: '2019-01-01',
        },
        {
          title: 'event2',
          start: '2019-01-02',
        },
        {
          title: 'event3',
          start: '2019-01-03',
        },
      ],
    };
  },
};
</script>
```

**Comment by comadaihiep92** [comment]
Please help, icon don't show on @ionic/angular 5.2.3.

how to fixed it?

`http://localhost:8100/svg/md-arrow-dropdown.svg 404 (Not Found)
 http://localhost:8100/svg/ios-arrow-back.svg 404 (Not Found)
http://localhost:8100/svg/ios-arrow-forward.svg 404 (Not Found)`

`$ ionic info

Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\lanth.UNITEK\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10`

**Comment by jongbonga** [comment]
@comadaihiep92 
`npm i “https://github.com/shaneparsons/ion2-calendar#76ae1e241183500a377647b363c931a03aa50bca"`

**Comment by myvictorlife** [comment]
Hi everyone,

I'm using pickMode: 'range' and it works well, but I'm having a problem in the following situation:
After selecting the start date and end date, I would like to select the start date and end date again. I would like the dates to be reset and to be possible select start date and end date again.
Today it is only possible for me to select the start date if I select a date between the 2 dates after selected.
I would like to have the same behavior that we have today on this site "https://www-yefjsqmtmv.now.sh/", always be possible to select start and end dates.

Example: 
Start date: "11"
End date: "14"

If i click the day "15", the end date is selected. 
Start date: "11"
End date: "15"

If i click the day "10", the start date is selected. 
Start date: "10"
End date: "15"

Not being able to select both at the same time.

**Comment by jongbonga** [comment]
@myvictorlife this issue is related to icons not displaying... yours is something else. create a seperate issue for it

**Comment by myvictorlife** [comment]
> @myvictorlife this issue is related to icons not displaying... yours is something else. create a seperate issue for it

Thanks @jongbonga, I removed the comment here and created an issue. https://github.com/hsuanxyz/ion2-calendar/issues/307

**Comment by SagarJHedau** [comment]
Thanks @shaneparsons

**Comment by LamJingJie** [comment]
Doesn't work for me. I tried to change my package-json-lock and package-json "ion2-calendar" to "https://github.com/shaneparsons/ion2-calendar#76ae1e241183500a377647b363c931a03aa50bca" stated above but to no avail.

I then tried to npm i "https://github.com/shaneparsons/ion2-calendar#76ae1e241183500a377647b363c931a03aa50bca" also did not work as it gives me this error:

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js install --cache=C:\Users\jingj\AppData\Local\npm-cache\_cacache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm ERR! code ERESOLVE
npm ERR! npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! npm ERR!
npm ERR! npm ERR! While resolving: ion2-calendar@3.4.1
npm ERR! npm ERR! Found: @angular/compiler@7.1.4
npm ERR! npm ERR! node_modules/@angular/compiler
npm ERR! npm ERR!   dev @angular/compiler@"7.1.4" from the root project
npm ERR! npm ERR!
npm ERR! npm ERR! Could not resolve dependency:
npm ERR! npm ERR! peer @angular/compiler@"7.2.16" from @angular/compiler-cli@7.2.16
npm ERR! npm ERR! node_modules/@angular/compiler-cli
npm ERR! npm ERR!   dev @angular/compiler-cli@"^7.2.9" from the root project
npm ERR! npm ERR!
npm ERR! npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! npm ERR!
npm ERR! npm ERR! See C:\Users\jingj\AppData\Local\npm-cache\_cacache\eresolve-report.txt for a full report.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\jingj\AppData\Local\npm-cache\_cacache\_logs\2021-01-14T05_17_36_783Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jingj\AppData\Local\npm-cache\_logs\2021-01-14T05_17_37_050Z-debug.log


Does anyone knows how to fix? Will be greatly appreciated :). Thanks

**Comment by mhmoudalaskalany** [comment]
may be it is too late answer but i face same issue today and i solved it by install latest stable version of the npm package don't install  
npm i ion2-calendar@next 

just install
npm i  ion2-calendar 
the icons should works fine
