### ISSUE TITLE
Scroll back not working

### ISSUE THREAD

**Issue by theocq** [HsuanXyz/ion2-calendar#29]
Scrolling calendar back to previous month is only possible after scrolling forward.
Tried with ion2-calendar/demo (Android).

**Comment by emrekara37** [comment]
Yes, I have the same problem

**Comment by skeltonm** [comment]
Does anyone have a fix for this issue?

**Comment by IT-MikeS** [comment]
I believe I've had the same issue. Here is what I did to allow for scroll back without scrolling forward first, I hope it helps with this issue.

```
   const options: CalendarModalOptions = {
      pickMode: 'range',
      title: '',
      from: moment().subtract(1, 'months'),
      canBackwardsSelected: true,
      defaultDateRange: {from: moment().format('YYYY-MM-DD'), to: moment().format('YYYY-MM-DD')},
      defaultScrollTo: moment(),
    };

    this.myCalendar = this.modalCtrl.create(CalendarModal, {
      options: options
    });
```

Basically I set the `from` option to 1 month less then my default selection then set `defaultScrollTo` to the default selection date (not sure if this helps but I just did it to make sure)

**Comment by AltRoot17** [comment]
, I have the same problem  :(

**Comment by radulescuandrew** [comment]
@IT-MikeS Your hacky solution works but this way I can't disable future dates anymore using **to** option.

**Comment by jeromedumas** [comment]
I have that same problem too :( Can somebody help us please???
