### ISSUE TITLE
Previous Month

### ISSUE THREAD

**Issue by juntaforce** [HsuanXyz/ion2-calendar#3]
Hi Hsuan,
 Nice plugin. Thanks for your effort.
But I need to see and  choose range with previous months days on calendar.
Is it possible??
Also how to make locale language with MMMM-yy ??
and how to disable days after today ??

**Comment by juntaforce** [comment]
First one is solved with
canBackwardsSelected:true
If you get a solution another questions, would be better if we querying past on calendar

**Comment by HsuanXyz** [comment]
> Also how to make locale language with MMMM-yy ??
(#4)
