### ISSUE TITLE
Calendar not working with Ionic --prod

### ISSUE THREAD

**Issue by theocq** [HsuanXyz/ion2-calendar#30]
With Ionic (latest) it's not possible to get calendar working with Ionic app-scripts-command "--prod".
Without "--prod" it's working correctly, with --aot it's also working.

You can try it with ion2-calendar/demo "ionic cordova run android --prod"

**Comment by jetav8r** [comment]
I'm having this same issue, but when I follow your link for the fix, I'm getting and error: 
uri is not registered (settings languages & frameworks schemas and dtds)  for the following code:
    xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
Any ideas?

**Comment by jetav8r** [comment]
I was able to fix this by deleting the www directory in both the root directory and platforms directory, then rebuilding.  Maybe this will help someone else

**Comment by agasbzj** [comment]
Build using:
ionic cordova build browser --prod
is still not working.
Error message is:
```
ERROR TypeError: Cannot read property 'create' of undefined(…)
g @ main.js:1
t.handleError @ main.js:2
e.handleError @ main.js:18(anonymous function) @ main.js:1
(anonymous function) @ main.js:10
t.invokeTask @ polyfills.js:3
inner.inner.fork.onInvokeTask @ main.js:3
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
invoke @ polyfills.js:3
```
Could you please fix that as soon as possible?

**Comment by HsuanXyz** [comment]
@agasbzj try `npm install @ionic/app-scripts@1.3.4`

**Comment by ANANDAN0693** [comment]
Me also facing the same issue  @HsuanXyz  so please help me solve this issue

**Comment by jetav8r** [comment]
This issue has also returned for me.  Deleting both www directories no longer solves the issue.  Now I can't use the calendar in the production version

**Comment by shamank** [comment]
Same for me. #42

**Comment by danielcrk** [comment]
I'm also seeing this issue. Any news about this?

**Comment by HsuanXyz** [comment]
Please use the latest version, and use ModalController instead of CalendarController.

**Comment by sean-hill** [comment]
I just installed this amazing library today, and got it working perfectly using `ionic serve`, but after using `ionic build ios --prod` it ends up looking this:

![image](https://user-images.githubusercontent.com/1205866/31041819-553be744-a550-11e7-92cb-7e17ea1a5f43.png)

Using this code:

```ts
const options: CalendarModalOptions = {
  pickMode: 'range',
  title: 'Select dates',
  closeIcon: true,
  doneLabel: 'Save'
}

const datePicker = this.modalCtrl.create(CalendarModal, {
  options: options
})

datePicker.present()

datePicker.onDidDismiss(date => {
  console.log(date)
})
```

Any ideas onto what may be happening here? Obviously it looks like the CSS is not being applied.

```
cli packages: (/Users/seanhill/Development/Freelance/BikerBuddy/mobile/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.0.0
    Node       : v8.4.0
    npm        : 5.3.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235
```

**Comment by HsuanXyz** [comment]
@sean-hill please open new issue

**Comment by fernandocode** [comment]
This problem still occurs, for those who could not reproduce the problem follows this [stackblitz](https://stackblitz.com/edit/ionic-vf4pex)

**Comment by Fidym** [comment]
> This problem still occurs, for those who could not reproduce the problem follows this [stackblitz](https://stackblitz.com/edit/ionic-vf4pex)

I'am facing the same issue, could you solve it?
