### ISSUE TITLE
ion2 calender not showing ios-arrow-forword & ios-arrow-back with latest ionic 5

### ISSUE THREAD

**Issue by neerajrk2509** [hsuanxyz/ion2-calendar#312]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] help me

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by DalterioRaffaele** [comment]
I have the same problem.
![Schermata 2020-09-11 alle 15 32 17](https://user-images.githubusercontent.com/32390496/92931673-1a096c00-f444-11ea-8c8e-ea45e29e593f.png)

**Comment by dromazmj** [comment]
Same here

**Comment by Metallink** [comment]
Same here, any idea?

**Comment by marrahi** [comment]
i have same problem, which is the path for add this????

**Comment by itsLucario** [comment]
People who are facing the issue can use my fork from the PR. I have done the fix

**Comment by AleksandrCherniavskiy** [comment]
@itsLucario Hi. Please write the command which I can install your fork by npm.

**Comment by SagarJHedau** [comment]
@itsLucario I tried to use your fork by following command
npm i https://github.com/itsLucario/ion2-calendar.git
 but while importing it say module not found....

Can you please help me for the proper command to configure. 

![Screenshot 2020-10-26 at 3 40 48 PM](https://user-images.githubusercontent.com/46328309/97159944-a1673080-17a1-11eb-9897-a5aaa3a259b1.png)

**Comment by itsLucario** [comment]
I have published my fork to @lucario/ion5-calendar

You can use it with `npm i @lucario/ion5-calendar`

**Comment by SagarJHedau** [comment]
Hello Hsuan,

Can you please let me know how can I set the default date in while using
range.

Also y does it give value undefined when i wont select range but only from
date?

Regards,
Sagar J Hedau
