### ISSUE TITLE
Calendar not returning data to Modal

### ISSUE THREAD

**Issue by oakerele** [HsuanXyz/ion2-calendar#34]
Let me start by saying this is a really great project that you have going here. I have a problem that is outlined below:

I have a button in a Modal that shows the calendar and when I click on the check icon to save the data, nothing is sent back to the Modal. Just to make sure I was doing the right thing, I copied my code to a page verbatim and it worked perfectly on there. Is there any work around for using this component in Modals? My code below

```ts
    this.calendarCtrl.openCalendar({
      isRadio: false,
      title: 'PartyUp Calendar',
      monthTitle: ' MMMM-yy',
      weekdaysTitle: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      from: new Date(),
      cssClass: 'calendar-class',
      to: yearFromNow,
      //isSaveHistory: true,
      closeLabel: 'CANCEL',
    })
      .then((res: any) => {
        console.log(res);
      })
      .catch((err) => {
        console.log("Error", err);
      });
```

**Comment by RakeshKW** [comment]
same for me .
its not returning data after selecting date

**Comment by oakerele** [comment]
According to something I saw somewhere, a Modal can't have another modal return data to it since it isn't an actual page. I ended up having to just make my modal into a page and then Calendar works fine.

**Comment by dkd051** [comment]
I have same issue.
