### ISSUE TITLE
Its possible to disable by date ?

### ISSUE THREAD

**Issue by ANANDAN0693** [HsuanXyz/ion2-calendar#35]
Its any possible to disable dates  by date in this calendar

**Comment by HsuanXyz** [comment]
```diff
daysConfig() {

    let _daysConfig = [
      {
        date:new Date(2017,0,1),
      },
      {
        date:new Date(2017,1,14),
+       disable:true
      },
      ...
    ];

    _daysConfig.push(...this.days);

    this.calendarCtrl.openCalendar({
      from: new Date(2017,0,1),
      to  : new Date(2017,11.1),
      daysConfig:_daysConfig
    })
      .then( (res:any) => { console.log(res) })
      .catch( () => {} )
  }
```

**Comment by shrankhlagarg** [comment]
Is it possible to disable the dates before a certain date? Thanks

**Comment by sckumar** [comment]
Code is not pushed yet? 
Days config doesn't have disable property in calendar.modal.ts.

**Comment by HsuanXyz** [comment]
`npm install ion2-calendar@2.0.0-beta.5 --save`

**Comment by karanianandkumar** [comment]
This issue is not fixed. I am unable to disable day.

**Comment by HsuanXyz** [comment]
Please update

**Comment by JAYiSON021** [comment]
Thanks for This :)
ion2-calendar is sooo Amazing!

**Comment by matheusfelixr** [comment]
Olá como vai você? Estou tentando desativar datas e não consigo, teria algum tutorial para explicar?

**Comment by matheusfelixr** [comment]
Hello how are you? I'm trying to disable dates and I can't, would there be any tutorial to explain?
