### ISSUE TITLE
can you add some additional API?

### ISSUE THREAD

**Issue by dungcmm** [HsuanXyz/ion2-calendar#36]
now your confirm button is √,can you render extra API to change confirm button's title, for example: "确定"? and can you render API, change Title's font size, font color,and confirm button's title font size and so on.

现在你的“确定”按钮是打勾，你能提供诸如改变确定按钮标题的API吗？还有改变calendar标题字体颜色、大小、“确定”按钮字体大小颜色、诸如此类的API吗？

**Comment by HsuanXyz** [comment]
Yes, I will improve.

**Comment by HsuanXyz** [comment]
https://github.com/HsuanXyz/ion2-calendar/releases/tag/2.0.0-beta.3
