### ISSUE TITLE
Close calendar when clicking on date

### ISSUE THREAD

**Issue by jetav8r** [HsuanXyz/ion2-calendar#38]
The previous version closed the calendar automatically after picking a date.  The new version (2.0.0-beta) has a Cancel and Done menu selection which you have to click on to close the calendar.
Is there an option to close the calendar immediately upon clicking on the selected date (instead of having to choose "Done")?

**Comment by HsuanXyz** [comment]
https://github.com/HsuanXyz/ion2-calendar/releases/tag/2.0.0-beta.3

**Comment by jetav8r** [comment]
Very good...thank you for adding this functionality back in!

**Comment by macduff111** [comment]
thanks, very welcome. would be good to add the autoDone option to the API documentation
