### ISSUE TITLE
Moment locale

### ISSUE THREAD

**Issue by A-contresens** [HsuanXyz/ion2-calendar#4]
I didn't manage to load moment locale to translate month name ?
How I can do it ? Where I have to import the import 'moment/locale/fr'; to make it translate ?

Thanks
very good calendar !

**Comment by HsuanXyz** [comment]
> English is not my native language; please excuse typing errors.

@A-contresens 
This plugin use date pipe format date, So you can refer to this link.
http://stackoverflow.com/a/39344889/6851836

```ts
import { NgModule, ErrorHandler, LOCALE_ID } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';

import { CalendarModule } from "ion2-calendar";

@NgModule({
  declarations: [
    MyApp,
    ...
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    CalendarModule,
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    ...
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler},
              { provide: LOCALE_ID, useValue: "zh-CN" }]
})
export class AppModule {}

```

**Comment by A-contresens** [comment]
Thank you

It is working great !

**Comment by JrkJesus** [comment]
Hi, I using ionic 3, i follow the code and my months labes dont change. I using modal options to display my calendar. Is there any problem with modal options? Or for ionic 3 need other code?

**Comment by juanmiret** [comment]
> Hi, I using ionic 3, i follow the code and my months labes dont change. I using modal options to display my calendar. Is there any problem with modal options? Or for ionic 3 need other code?

I'm having this exact issue!

**Comment by Iscbr** [comment]
I have been found the solution to put month names with correct locale, you need to add the following line:

`Only add this line.
require('moment/locale/es-mx');

@NgModule(...)
export class AppModule {}`

I used 'es-MX' but you can put whatever you need.
