### ISSUE TITLE
showYearPicker and other features not working with Ionic v3

### ISSUE THREAD

**Issue by shamank** [HsuanXyz/ion2-calendar#40]
Hi! I followed the instructions to implement it in my Ionic app (I'm using latest @3.5.0). It works good but I can't find some cool options like the ones in: https://hsuanxyz.github.io/demo/ion2-calendar/
After examining the source, I realized those were not included in the source installed from npm: showYearPicker, closeIcon, etc...

Is there any way I can get those working too? Thanks!

**Comment by HsuanXyz** [comment]
run `npm install ion2-calendar@beta --save`

**Comment by shamank** [comment]
Thanks man! That worked.

**Comment by HsuanXyz** [comment]
https://github.com/HsuanXyz/ion2-calendar/releases/tag/2.0.0-beta.3
