### ISSUE TITLE
Can't see it after compiling

### ISSUE THREAD

**Issue by shamank** [HsuanXyz/ion2-calendar#42]
Hi. I can use it when running with `ionic serve` but when compiling with: `ionic package build android --profile=production --release --prod` it doesn't show on device. Any advice? Thanks.

**Comment by shamank** [comment]
I can confirm it's because of "--prod" param that minifies and uglifies the code. Without `--prod` it's working on device as well.

**Comment by HsuanXyz** [comment]
Please use the latest version, and use ModalController instead of CalendarController.
