### ISSUE TITLE
Calendar is not showing properly after upgrading ionic app-script .

### ISSUE THREAD

**Issue by RakeshKW** [HsuanXyz/ion2-calendar#43]
I am developing app using ionic 2.

issue:
calendar is not showing properly when ionic app-script is upgraded to latest version...
latest version is "@ionic/app-scripts": "2.0.0"

but it is working when we install older ionic app-script version
old version is "@ionic/app-scripts": "1.3.8"

So please make this calendar working properly for latest app-script version.

**Comment by HsuanXyz** [comment]
Please use the latest version, and use ModalController instead of CalendarController.
