### ISSUE TITLE
Week Start Day

### ISSUE THREAD

**Issue by pedrocortizo** [HsuanXyz/ion2-calendar#5]
Hi

Very pretty plugin for ionic2 apps, Thank you.

Is there any way to establish **the first day of the week**?

By default the calendar starts the weeks on **Sunday**, but in Europe (Spain) it is usual to present the calendars **beginning on Monday.**

It would be possible to include a configuration variable "**weekFirstDay**" with values ​​0 for Sunday, 1 for Monday, which allows us to set the starting day of the rendered calendar.

Even an option to set a Locale would be perfect, allowing to set an array of options with the format of the date, or the weekFirstDay that I proposed earlier.

Thank you!

**Comment by HsuanXyz** [comment]
@pedrocortizo is ok now.

**Comment by sckumar** [comment]
@HsuanXyz , Week start day is keep adding one day if the history is turned on.

**Comment by HsuanXyz** [comment]
@sckumar try #53
