### ISSUE TITLE
Calendar is not showing 

### ISSUE THREAD

**Issue by RakeshKW** [HsuanXyz/ion2-calendar#50]
when i build android app with this command :-"ionic cordova run android " ,it is working fine.
but i build using this command :-"ionic cordova run android --prod" ,it is not showing.
"ionic cordova run android --prod"  command is used for removing white screen after splash screen, so that app should start faster.

**Comment by HsuanXyz** [comment]
try [#30](https://github.com/HsuanXyz/ion2-calendar/issues/30#issuecomment-310081504)

**Comment by RakeshKW** [comment]
i tried #30 , but Still its not working for me.
Is it working for u?

**Comment by HsuanXyz** [comment]
Is there an error message? please tell me.

**Comment by RakeshKW** [comment]
actually i building and installing app in my mobile. And in mobile on button click i am calling only range calendar . So when click on button nothing is happening and no error is showing.
and if there is error in background then i can't see because i am testing in mobile.

**Comment by HsuanXyz** [comment]
Please use the latest version, and use ModalController instead of CalendarController.
