### ISSUE TITLE
Multi select date.

### ISSUE THREAD

**Issue by brunofasolin22** [HsuanXyz/ion2-calendar#51]
Would there be any way to make a multi selection of dates? for example 3 or 4 dates

**Comment by HsuanXyz** [comment]
Thank your issues.
Already supported,but not yet released.

<img width="337" alt="multi 7" src="https://user-images.githubusercontent.com/22736418/29004288-931035de-7a8a-11e7-99fe-f1d148d663e1.png">

**Comment by msyahidin** [comment]
+1

**Comment by HsuanXyz** [comment]
`npm install ion2-calendar@2.0.0-beta.5 --save`

```diff
this.calendarCtrl.openCalendar({
      from: new Date(2017,1,1),
      ...
+     pickMode: 'multi', // 'multi', 'range', 'single'
      ...
    })
```
