### ISSUE TITLE
weekdaysTitle Bug

### ISSUE THREAD

**Issue by MiguelHernandezCh** [HsuanXyz/ion2-calendar#53]
When I reopen the calendar the days title move, original state:

![image](https://user-images.githubusercontent.com/22020959/29253977-917ff4b8-8050-11e7-9e03-71da5d5d8966.png)

-------------------------------------------------

![image](https://user-images.githubusercontent.com/22020959/29253986-9debe298-8050-11e7-8723-e40e0d4d0a97.png)

-------------------------------------------------

![image](https://user-images.githubusercontent.com/22020959/29253988-aa916414-8050-11e7-9b55-d217da3a824d.png)

This is my original array `["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"]`
The week starts on monday 

How can I fix this issue? Thank you!

**Comment by HsuanXyz** [comment]
Tell me your all options, thank

**Comment by MiguelHernandezCh** [comment]
this.calendarCtrl.openCalendar({
            from: new Date(),
            title: 'Calendario',
            closeLabel: Cerrar,
            cssClass: 'bookTripCal',
            weekdaysTitle: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
            daysConfig: this.daysConfig,
            weekStartDay: 1,
        }, {
            showBackdrop: false,
            enableBackdropDismiss: false
        }).then(res => {
            this.trip.departureDate = res.date.time;
        })
            .catch((error) => {
                console.log(error);
            });

@HsuanXyz

**Comment by MiguelHernandezCh** [comment]
Can you help me? @HsuanXyz

**Comment by HsuanXyz** [comment]
Sorry~ try this.

`npm install ion2-calendar@2.0.0-beta.5 --save`

```javascript
 openCalendar() {
    this.calendarCtrl.openCalendar({
      weekdays: ['7', '1', '2', '3', '4', '5', '6'],
      weekStart: 1,
    })
      .then(res => console.log(res))
      .catch(err => console.log(err))
  }
```

**Comment by MiguelHernandezCh** [comment]
Thank you! @HsuanXyz
