### ISSUE TITLE
Not working with Ionic 3.6

### ISSUE THREAD

**Issue by gopalaiahvinay** [HsuanXyz/ion2-calendar#57]
Hi,

I was trying out your plugin for my Ionic 3.6 app. 
When I click the button to open the calendar, I am getting an error saying, that there is no CalendarPage declared in Entry Components. 

### appointment.html
```
<!--
  Generated template for the AppointmentsPage page.

  See http://ionicframework.com/docs/components/#navigation for more info on
  Ionic pages and navigation.
-->
<ion-header>

  <ion-navbar color="primary">
    <ion-title>Upcoming Appointments</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>
  <ion-list>
    <ion-item (tap)="openCalendar()" >
      Current Date: {{curDate | date: 'dd-MMM-yyyy'}}
    </ion-item>
  </ion-list>
</ion-content>

```

### appointment.ts
```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { CalendarController } from "ion2-calendar/dist";
/**
 * Generated class for the AppointmentsPage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-appointments',
  templateUrl: 'appointments.html',
})
export class AppointmentsPage {
  curDate = new Date();
  constructor(public navCtrl: NavController,
    public navParams: NavParams,
    public calendarCtrl: CalendarController) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad AppointmentsPage');
  }
  openCalendar() {
    this.calendarCtrl.openCalendar({
      from: new Date()
    })
      .then(res => { console.log(res) });
  }
}
```

### appointment.module.ts 
```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { AppointmentsPage } from './appointments';
import { CalendarModule, CalendarPage } from "ion2-calendar";
@NgModule({
  declarations: [
    AppointmentsPage
  ],
  imports: [
    CalendarModule,
    IonicPageModule.forChild(AppointmentsPage),
  ],
})
export class AppointmentsPageModule {}
```
## Ionic Information 
```
 @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.1.0
    npm  : 5.0.3
    OS   : Windows 10
```

#### Appointment Page Before Clicking On Date 
![calendar 1](https://user-images.githubusercontent.com/4154510/29363669-8628ab40-82ae-11e7-831d-af70a3594e6f.png)

#### Appointments Page After Clicking On Date [Error] 
![calendar 2 error](https://user-images.githubusercontent.com/4154510/29363706-a4129e04-82ae-11e7-92b8-eae7b5a02de7.png)

**Comment by HsuanXyz** [comment]
Do you use lazy loading?

**Comment by gopalaiahvinay** [comment]
Yes

**Comment by rflorat07** [comment]
**Work for me with Ionic 3.6 and  lazy loading **

    Cordova Platforms        : android 6.1.2 ios 4.3.1
    Cordova CLI              : 6.5.0
    Ionic Framework          : ionic-angular 3.6.0
    Ionic CLI                : 3.10.3
    Node       	         : v6.10.0
    npm        		 : 5.3.0
    ios-deploy 		 : 1.9.1
    ios-sim    		 : 5.0.13
    OS         		 : macOS Sierra
    Xcode      		 : Xcode 8.3.3 Build version 8E3004b

**Comment by zuo305** [comment]
I have same issue. Sorry, i am not sure what means lazy-load in this part. By the way this lib save my live. Thank you very much.

**Comment by HsuanXyz** [comment]
[lazyload-demo](https://github.com/HsuanXyz/ion2-calendar/tree/master/lazyload-demo)

**Comment by chaitraravindranath** [comment]
lazyload-demo link is not working. I want to refer this. Can you plz check it and make it work?

**Comment by arupnayak** [comment]
> [lazyload-demo](https://github.com/HsuanXyz/ion2-calendar/tree/master/lazyload-demo)

@HsuanXyz Can you make the code available again? Link is not working
