### ISSUE TITLE
Are dates only returned as strings when not in modal mode?

### ISSUE THREAD

**Issue by promethyttrium** [HsuanXyz/ion2-calendar#59]
It would seem the demo code showing the selected dates via [(ngModel)] are always returned as strings given the format attribute. Is it possible to return the dates as their original Date() type?

**Comment by HsuanXyz** [comment]
Not supported now, thanks for feedback.

**Comment by HsuanXyz** [comment]
@promethyttrium  
```bash
npm install ion2-calendar@2.0.2 --save
```

```html
<ion-calendar [(ngModel)]="date"
              type="js-date">
 </ion-calendar>
```
All type: `'string' | 'js-date' | 'moment' | 'time' | 'object'`

**Comment by promethyttrium** [comment]
Thanks for the quick turnaround!! Can't wait to try it out!
