### ISSUE TITLE
Add custom color option

### ISSUE THREAD

**Issue by niklilland** [HsuanXyz/ion2-calendar#61]
I love this! I just wish we could pass in a custom hex color, rather than specify an ionic scss variable. Would this be possible as a feature?

**Comment by HsuanXyz** [comment]
> ./src/theme/variables.scss
```diff
$colors: (
  primary:    #488aff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
+ cal-color:  #ff8732
);
```

> ./sec/pages/component/component.ts
```diff
 openCalendar() {
    const options = {
+     color: 'cal-color',
    };
    let myCalendar =  this.modalCtrl.create(CalendarModal, {
      options: options
    });

    myCalendar.present();

    myCalendar.onDidDismiss(date => {
      console.log(date);
    })
  }
```

This is a default value, you can change it.

**Comment by niklilland** [comment]
But this does not work, does it?

` openCalendar() {
    const options = {
+     color: '#eb3300',
    };
    let myCalendar =  this.modalCtrl.create(CalendarModal, {
      options: options
    });

    myCalendar.present();

    myCalendar.onDidDismiss(date => {
      console.log(date);
    })
  }`

**Comment by HsuanXyz** [comment]
Yes, You need to declare `cal-color` in variables.scss

**Comment by niklilland** [comment]
I have a color variable that changes depending on the user's selection, and from what I can tell, replacing 'cal-color' can only be replaced by another scss variable, not something dynamically changing constantly, right?

**Comment by HsuanXyz** [comment]
It is immutable.

**Comment by HsuanXyz** [comment]
Use hex color performance is not good, I can not add this feature. So sorry~

**Comment by niklilland** [comment]
I understand. Thank you anyways, it is still a fantastic library, please keep up the great work!
