### ISSUE TITLE
在ionic2.0beta上 报了n多错误 ...

### ISSUE THREAD

**Issue by zhoupIT** [HsuanXyz/ion2-calendar#62]
/ion2-calendar/calendar.model.ts(83,64): Error TS1110: Type expected.
ion2-calendar/calendar.model.ts(116,52): Error TS1110: Type expected.
ion2-calendar/components/calendar.modal.ts(85,34): Error TS1110: Type expected.
ion2-calendar/components/calendar.modal.ts(85,40): Error TS1109: Expression expected.
ion2-calendar/components/month.component.ts(72,30): Error TS1110: Type expected.
ion2-calendar/components/month.component.ts(72,36): Error TS1109: Expression expected.
ion2-calendar/services/calendar.service.ts(205,56): Error TS1110: Type expected.
ion2-calendar/services/calendar.service.ts(206,11): Error TS1005: ':' expected.
ion2-calendar/services/calendar.service.ts(206,72): Error TS1005: ',' expected.
ion2-calendar/services/calendar.service.ts(207,9): Error TS1005: ':' expected.
ion2-calendar/services/calendar.service.ts(207,20): Error TS1005: ',' expected.
ion2-calendar/services/calendar.service.ts(207,40): Error TS1005: ',' expected.
ion2-calendar/services/calendar.service.ts(207,47): Error TS1109: Expression expected.
ion2-calendar/services/calendar.service.ts(214,3): Error TS1128: Declaration or statement expected.
ion2-calendar/services/calendar.service.ts(216,26): Error TS1005: ',' expected.
......

**Comment by HsuanXyz** [comment]
ion2-calendar2.x 之后不兼容 ionic2. 因为官方升级了 typescript, 我也必须升级，不然新版本也无法使用。建议你升级到最新的 ionic3.x，如果你想继续使用 ionic2.x，可以降级为 ion2-calendar1.x。

ps: 使用 `npm view ion2-calendar ` 查看历史版本，然后通过 npm install  ion2-calendar@版本号 --save` 安装指定版本。
