### ISSUE TITLE
Add different events for Cancel and Done  for Modal Mode.

### ISSUE THREAD

**Issue by haroldhalcyon28** [HsuanXyz/ion2-calendar#65]
It returns an error because Cancel is also known as Dismiss button. Or can I just have diff way instead of using onDidDismiss to return data? Thanks for this by the way. Great work

**Comment by HsuanXyz** [comment]
`npm install ion2-calendar@2.0.4 --save`

```typescript
basic() {
    const options = {
      title: 'BASIC'
    };
    let myCalendar =  this.modalCtrl.create(CalendarModal, {
      options: options
    });

    myCalendar.onDidDismiss((date, type) => {
      console.log(type); // 'cancel' | 'done'  | 'backdrop'
    })

    myCalendar.present();
  }
```

**Comment by haroldhalcyon28** [comment]
Thanks for this. I also discover that the error before occurs only on browser debugging but works perfectly on a device.
