### ISSUE TITLE
looks like the calendar can't get its CSS files

### ISSUE THREAD

**Issue by karimessouabni** [HsuanXyz/ion2-calendar#67]
The calendar is not showing properly. I followed the installation instructions for the 2 methodes (Components Mode & Modal Mode) this is how my project looks like :  
Lignes added :
**- app.module.ts :** 
import { CalendarModule } from "ion2-calendar
…
 imports: [
    BrowserModule,
    HttpModule,
    CalendarModule,…

**- MyPage.ts :**
import { CalendarModal, CalendarModalOptions, DayConfig } from "ion2-calendar";
import {CalendarController} from "ion2-calendar/dist";
…
constructor(
    public modalCtrl: ModalController,
  )
…
 openCalendar() {
  …
  }

**- MyPage.html:**
<button (click)="openCalendar()">Show Calendar</button>

        <ion-calendar [(ngModel)]="date"
        (onChange)="onChange($event)"
        [type]="type"
        [format]="'YYYY-MM-DD'">

And this is the result i'm getting : 
 
![capture d ecran 2017-09-26 a 02 30 18](https://user-images.githubusercontent.com/1681953/30837263-e7b9fb3c-a263-11e7-9380-a154debf82dc.png)

I already tried to install the older version 1.1 but still getting the same problem. 
Thank you in advance for your help

**Comment by HsuanXyz** [comment]
Hi, @karimessouabni can you run the `ionic info`  in your project ?

**Comment by arrunn** [comment]
I'm also facing the same issue, here my ionic info 
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.0.1

System:

    Android SDK Tools : 25.2.5
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy
`
@HsuanXyz 

![snip20170926_1](https://user-images.githubusercontent.com/1962403/30848754-b2f6f800-a2bd-11e7-9716-d42f2e4c5b2f.png)

**Comment by HsuanXyz** [comment]
I used ` @ionic/app-scripts@1.3.0` and `ionic-angular@3.0.1`, can not reproduction of the problem.
You can use `ionic start test` new a project, reproduction of the problem?

**Comment by karimessouabni** [comment]
That's what I'm getting when I run the Ionic info : 

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : not installed

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v8.4.0
    npm   : 5.3.0 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b 

Thank you for your help.

**Comment by arrunn** [comment]
Tried `ionic start test` and installed this plugin in new ionic project, still getting same issue. Please check the screenshot again.

![image](https://user-images.githubusercontent.com/1962403/30859521-b9838138-a2e1-11e7-8dd7-848644c70019.png)

**Comment by karimessouabni** [comment]
I restarted my computer and everything is working perfectly now. 
@arrunn Try restarting your ionic server, I think it could solve the problem.

**Comment by arrunn** [comment]
Yeah its working now, thanks @karimessouabni.

**Comment by kedar2594** [comment]
Worked like charm after restarting ionic serve :) Thank you @karimessouabni
