### ISSUE TITLE
Date-Range enhancement

### ISSUE THREAD

**Issue by dave2sidefyn** [HsuanXyz/ion2-calendar#7]
Hi thanks for your work!

It would be nice, if the calendar does not close immediatly when a 2nd date for a range is selected. It would be nice if you can see the selected range and then accept with a button.

**Comment by HsuanXyz** [comment]
Thank you!
This would be a big feature that I would consider adding

**Comment by HsuanXyz** [comment]
npm install ion2-calendar@2.0.0-beta.5 --save
