### ISSUE TITLE
Calendar presenting duplicate month - October

### ISSUE THREAD

**Issue by tiagoapolo** [HsuanXyz/ion2-calendar#70]
### Both on modal and embedded calendars it shows me duplicated October months.

- `I'm using ionic 2.1.18` in a **Web App**

<img width="608" alt="captura de tela 2017-09-27 as 11 58 04" src="https://user-images.githubusercontent.com/2777865/30920815-4bb320b0-a37b-11e7-900a-ad75d46bbeee.png">

- The Date object understand the second occurrence of October as November 

<img width="402" alt="captura de tela 2017-09-27 as 11 57 18" src="https://user-images.githubusercontent.com/2777865/30920720-0f021e96-a37b-11e7-8244-1f27ac1d2f1d.png">

**Comment by HsuanXyz** [comment]
try
```typescript
 openCalendar() {
    const options: CalendarModalOptions = {
      monthFormat: 'yyyy-MM'
    };
    let myCalendar =  this.modalCtrl.create(CalendarModal, {
      options: options
    });

    myCalendar.present();

    myCalendar.onDidDismiss(date => {
      console.log(date);
    })
  }
```

**Comment by tiagoapolo** [comment]
@HsuanXyz it has something to do with the value that comes from `monthFormatFilterStr` and originally `monthFormat` 

I think this is related to the month formatting and my `localeDateString`

I think today I can give you a proposed fix for this.

<img width="602" alt="captura de tela 2017-10-02 as 14 33 35" src="https://user-images.githubusercontent.com/2777865/31090755-208f8920-a77f-11e7-9092-81f27cb79b3f.png">

**Comment by zuo305** [comment]
Same issue. Thanks. 
Strange thing is some computer is correct, some is wrong.
