### ISSUE TITLE
Bug: on set ngModel value for a date next month the calendar does not navigate to that month

### ISSUE THREAD

**Issue by murraybauer** [HsuanXyz/ion2-calendar#71]
Awesome lib btw!

Using:
`pickMode: 'single', 
type:'moment`

If run this code on a button
`this.date = this.date.clone().add(5, 'days')`

When the new date value is in the next month, whilst it is selected the calendar, does not navigate the selected month.

I have similar issues when using the calendar on an edit form and wish to display the persisted value - the month always shows the current month, not the month base upon the select value.

**Comment by HsuanXyz** [comment]
Hi @murraybauer , Thank your issue, please upgrade the version.

`npm install ion2-calendar@2.0.5 --save`

![addm](https://user-images.githubusercontent.com/22736418/31055642-964c44ea-a68b-11e7-8b97-8b6db15adedc.gif)

**Comment by murraybauer** [comment]
@HsuanXyz thx. Perfect - this fixed the issue when I select a date on the calendar, then run a function like the below to increment it:
`this.date = this.date.clone().add(25, 'days')`

It maybe unrelated to this bug, but I still can't get the calendar to select the date on the calendar base upon the variable value original bound to ngModel such as:
`public date: any = moment().add(5, 'd')`

I see there is a `defaultDate` parm, but this only appears on the Modal options.

My total code
```
public date: any = moment().add(5, 'd')
public increment() {
   this.date = this.date.clone().add(25, 'd')
}
```

**Comment by HsuanXyz** [comment]
```
public date: any = moment(moment().format('YYYY-MM-DD')).add(5, 'd') 
```

**Comment by murraybauer** [comment]
@HsuanXyz worked - thank you so much!
