### ISSUE TITLE
Error: Missing css after update ionic 3.7.1 and build  my project 

### ISSUE THREAD

**Issue by rflorat07** [HsuanXyz/ion2-calendar#75]
After update to Ionic 3.7.1 and build my project  **ionic cordova build ios --prod** , the css of the ion2-calendar was not inserted in my App with the --prod flag... any idea ?

` 
cli packages: 

    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    Node       : v6.10.0
    npm        : 5.4.2
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9A235`

**Comment by HsuanXyz** [comment]
duplicated [#73](https://github.com/HsuanXyz/ion2-calendar/issues/73#issuecomment-333402640)
