### ISSUE TITLE
Not working with Ionic 2?

### ISSUE THREAD

**Issue by marko1943** [HsuanXyz/ion2-calendar#76]
Hi, has something changed since last commit but the docs havent been updated?

I'll provide more info here later... 

Basically, I have imported CalendarModule in modules, and added it to imports...

And after i run the app i get

> "let-" is only supported on template elements. ("
> 
>       <div #months>
>         <ng-template ngFor [ERROR ->]let-month [ngForOf]="calendarMonths" [ngForTrackBy]="trackByTime" let-i="index">
>           <div class"): CalendarModal@42:27
> "let-" is only supported on template elements. ("onths>
>         <ng-template ngFor let-month [ngForOf]="calendarMonths" [ngForTrackBy]="trackByTime" [ERROR ->]let-i="index">
>           <div class="month-box" [attr.id]="'month-' + i">
>             <h4 class="text"): CalendarModal@42:93
> Error: Template parse errors:
> "let-" is only supported on template elements. ("
> 
>       <div #months>
>         <ng-template ngFor [ERROR ->]let-month [ngForOf]="calendarMonths" [ngForTrackBy]="trackByTime" let-i="index">
>           <div class"): CalendarModal@42:27
> "let-" is only supported on template elements. ("onths>
>         <ng-template ngFor let-month [ngForOf]="calendarMonths" [ngForTrackBy]="trackByTime" [ERROR ->]let-i="index">
>           <div class="month-box" [attr.id]="'month-' + i">
>             <h4 class="text"): CalendarModal@42:93

this is for "ion2-calendar": "^2.0.6", which installs automatically 

my ionic info

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 2.3.0

**Comment by marko1943** [comment]
@ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 2.3.0

**Comment by marko1943** [comment]
When I run demo its all good but not with my project

**Comment by ajin1001** [comment]
i am getting same error with ionic 2

**Comment by HsuanXyz** [comment]
Yes, need to upgrade the ionic to 3.0.0+.
Guide: https://github.com/ionic-team/ionic/releases
