### ISSUE TITLE
First day of week changes every time you open the modal

### ISSUE THREAD

**Issue by JorgeSanchezGr** [HsuanXyz/ion2-calendar#77]
When you set weekStart and weekDays options, and open twice the modal, first day label changes every time you open.

Options:
![captura de pantalla 2017-10-06 a las 11 56 35](https://user-images.githubusercontent.com/15929281/31273145-aee4b464-aa8d-11e7-822e-faddc7e87270.png)

First open:
![captura de pantalla 2017-10-06 a las 11 57 50](https://user-images.githubusercontent.com/15929281/31273147-aeef47ee-aa8d-11e7-9a89-e2ecc0125996.png)

Second open:
![captura de pantalla 2017-10-06 a las 11 58 03](https://user-images.githubusercontent.com/15929281/31273146-aeeb5c9c-aa8d-11e7-92cb-ebe26cf1738f.png)

**Comment by JorgeSanchezGr** [comment]
I just make a pull request solving this.

**Comment by HsuanXyz** [comment]
Thank for your PR, has been merged into the latest release.
