### ISSUE TITLE
Give option to not wrap in a modal! 

### ISSUE THREAD

**Issue by maitham1** [HsuanXyz/ion2-calendar#8]
It would be awesome if rather than forcing the user to use a modal controller, thy can just use HTML tags to render your calendar in the view. This would allow a lot more flexibility and the user could dictate when the calendar should be dismissed

**Comment by NBAMj** [comment]
👍

**Comment by tryadelion** [comment]
any news? this would be an amazing improvement

**Comment by HsuanXyz** [comment]
Developing
<img width="462" alt="screen shot 2017-07-04 at 8 55 16 pm" src="https://user-images.githubusercontent.com/22736418/27830934-35550ca0-608e-11e7-8c71-d493c83101d5.png">

**Comment by sascha1337** [comment]
please update this and give us that calendar without modal plx thx

**Comment by HsuanXyz** [comment]
Please update
