### ISSUE TITLE
'ion-calendar' is not a known element:

### ISSUE THREAD

**Issue by 18bit** [HsuanXyz/ion2-calendar#82]
'ion-calendar' is not a known element:
我的页面是这样写的，

`
  <ion-card>
    <ion-card-content>
      <ion-card-title>
        basic
      </ion-card-title>
      <ion-calendar class="my-calendar"
                    [(ngModel)]="date"
                    [type]="'moment'">
      </ion-calendar>
      <p>{{date}}</p>
    </ion-card-content>
  </ion-card>`

然后报了下面的这个错 。请问这个该怎么解决
Can't bind to 'type' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'type' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ion-calendar class="my-calendar"
                    [(ngModel)]="date"
                    [ERROR ->][type]="'moment'">
      </ion-calendar>
      <p>{{date}}</p>
"): ng:///TestdatepickerPageModule/TestdatepickerPage.html@17:20

**Comment by HsuanXyz** [comment]
是否使用懒加载

**Comment by 18bit** [comment]
是的  ，参考了你的懒加载的demo 也是同样的错

**Comment by 18bit** [comment]
。。。。

import { CalendarModule } from "ion2-calendar";


import { OrderBy } from './../pipes/order-by';

@NgModule({
  declarations: [
    MyApp,
    OrderBy,
    DatePicker
  ],
  imports: [
    BrowserModule,
    HttpModule,
    CommonModule,
    IonicModule.forRoot(MyApp,{
    	iconmode:'ios',
    	mode:'ios',
    	backButtonText: ''//返回按钮的文字  	
    }),
    CalendarModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    DatePicker
  ],
。。。。

**Comment by HsuanXyz** [comment]
这里不需要，在你的 Testdatepicker.module.ts 引入
