### ISSUE TITLE
Options can not be changed once rendered

### ISSUE THREAD

**Issue by murraybauer** [HsuanXyz/ion2-calendar#84]
Once the calendar component is rendered, any changes to the options object is not reflected on the calendar.
  
My specific use cases are to:
1) On switching to another month (e.g. on monthChange event), update the daysConfig options with new data for the current month - lazy loaded (locally generated or remote ajax)
2) switch between 'single' and 'multi' pick modes using the same calendar.  

If I reference the component in the template using a variable `#mycal`, and call mycal.ngOnInit() after I update the options the calendar updates perfectly.

I suspect all you need to do to fix this is add this line to your source calendar.component.ts file so any change to it's input variables causes it to re-run the initialisation code which doesn't seem to have any adverse side effects that I can see.

```
ngOnChanges(changes: SimpleChanges) {
    this.ngOnInit()
  }
```

**Comment by 13868620741** [comment]
我也有这个问题，请作者帮忙解决一下！

**Comment by HsuanXyz** [comment]
update to `ion2-calendar@2.0.10`

```typescript
monthChange($event) {
    let date = moment($event.newMonth.string, 'YYYY-MM-DD');
   // mock async
    setTimeout(() => {
      const newPot = {
        daysConfig: [
          {
            date: date.toDate(),
            marked: true,
          },
          {
            date: date.clone().add(1, 'd').toDate(),
            marked: true,
          }
          ,
          {
            date: date.clone().add(2, 'd').toDate(),
            marked: true,
          }
        ]
      };

      this.optionsBasic = {
        ...this.optionsBasic,
        ...newPot
      };
    }, 300)
  }
```
