### ISSUE TITLE
Changes in monthPickerFormat options are not reflected on The Component Month button label.

### ISSUE THREAD

**Issue by joao-gsneto** [HsuanXyz/ion2-calendar#86]
I have translated monthPickerFormat to our country.
APR -> ABR
DEC -> DEZ
OCT -> OUT

But on the component change month label the month are still on english format (OCT, DEC, FEB)....
The changes maded on the option are not reflected on this label on the component.

I will be happy to help by sending a pull request correcting this if you find it useful or if it is something simple to do, it is only here that issue

**Comment by samuellessa** [comment]
Hi, i had a similar issue. The code below solved it for me! Hope it Helps!!!!!!

import {LOCALE_ID} from '@angular/core';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [{provide: LOCALE_ID, useValue: 'pt-BR'}]
})

**Comment by HsuanXyz** [comment]
@joao-gsneto https://github.com/HsuanXyz/ion2-calendar/issues/4#issuecomment-292398668 Hope to help you
