### ISSUE TITLE
Show year picker is commented

### ISSUE THREAD

**Issue by JorgeSanchezGr** [HsuanXyz/ion2-calendar#87]
Im trying to set showYearPicker option, but i've just seen that is commented on the code.Is there a problem with this option?

src/components/calendar.modal.ts
![captura de pantalla 2017-10-23 a las 18 14 03](https://user-images.githubusercontent.com/15929281/31900211-00ee8da0-b81e-11e7-8217-8d99b2e0d748.png)
Regards

**Comment by HsuanXyz** [comment]
Temporarily deprecated in the modal mode
