### ISSUE TITLE
Default Range Selection and RangeDisplay using CalendarComponentOptions

### ISSUE THREAD

**Issue by PDawda** [HsuanXyz/ion2-calendar#89]
I want to have only two months shown by default and a certain range in selected mode in the my Ionic 2 Modal Controller.  I am using a custom template using <ion-calendar> tag.

By default I see only one month displayed if I use <ion-calendar> tag in my template.
How do I get more than one month displayed ? and how do I set a range selected by default when modal popup opens up.

**Comment by HsuanXyz** [comment]
use `defaultDateRange `  options set range selected.
