### ISSUE TITLE
onChange event => what changed?

### ISSUE THREAD

**Issue by rokelvisar** [HsuanXyz/ion2-calendar#90]
Is it possible to know what changed when a date is tapped?

**Comment by HsuanXyz** [comment]
#### Components Mode
```html
<ion-calendar [(ngModel)]="date"
              (onChange)="onChange($event)">
<!--           ^^^^^^^^^                 -->
</ion-calendar>
```

#### Modal Mode
not support

**Comment by rokelvisar** [comment]
Hi, but this $event variable only has array of dates (in case of multi- date widget), It would like to see which date was changed (added or removed) - or even better - only return the date clicked. 

My scenario: 
on date touch I would like to display popover with some fields (radio/toggle/checkbox) and then inject this data to calendar. For that I need event on date clicked ... So my dates would have additional properties ... is this possible?

**Comment by rokelvisar** [comment]
Currently this is what I get from parameter $event: 
![image](https://user-images.githubusercontent.com/8679672/33100103-817a5376-cf13-11e7-96b3-35b2c2294744.png)
