### ISSUE TITLE
Support for gesture control

### ISSUE THREAD

**Issue by NBAMj** [HsuanXyz/ion2-calendar#91]
How about adding **gesture control support** to switch between months?
I think its an intuitive UX design.

I'm reading ionic docs and I'll see if I can add this feature myself.

**Comment by HsuanXyz** [comment]
supported in the next version.

**Comment by HsuanXyz** [comment]
`npm i ion2-calendar@2.1.0 --save`

**Comment by NBAMj** [comment]
Great work, thanks for swift update 👍
