### ISSUE TITLE
Bug style in date rage of same day

### ISSUE THREAD

**Issue by augustolima** [HsuanXyz/ion2-calendar#95]
There's a bug in the style when I select the same day in a date range.
I think it should be a red circle.

![range bug](https://user-images.githubusercontent.com/2763154/32734804-cd231a04-c871-11e7-9471-90b18ea4e3b3.PNG)

**Comment by HsuanXyz** [comment]
You are right, thanks for feedback.

**Comment by HsuanXyz** [comment]
`npm install ion2-calendar@2.1.3`
